#!/bin/env sh

update_bat () { 
	STATUS=$(cat /sys/class/power_supply/BAT0/status)
	val=$(cat /sys/class/power_supply/BAT0/capacity)

	LOWTHRES=20
	MIDTHRES=60
	COLOR="#006700"

	if [ $val -lt $MIDTHRES ]; then COLOR="#8d6b21"; fi
	if [ $val -lt $LOWTHRES ]; then COLOR="#670000"; fi

	bat="^b$COLOR^ $val% ^d^"
}
