#!/bin/env sh

startup () {
	 #services
	 volumeicon &
	 picom -b &

	 #
	 xwallpaper --center $HOME/.wallpapers/default.jpg

	 #custom
	 firefox &
	 setxkbmap -option grp:alt_shift_toggle -layout us,ar
}
